stages:
  - test

image: registry.gitlab.steamos.cloud/steam/steamos-docker-images/holo-main/base:latest

run_pytest:
  stage: test
  tags:
    - docker
    - linux
  script:
    - pacman -Sy --noconfirm --needed dbus-python python-pip
    - python -m venv --system-site-packages venv
    - . venv/bin/activate
    - pip install .[pytest]
    - dbus-run-session pytest

lint:
  stage: test
  tags:
    - docker
    - linux
  script:
    - pacman -Sy --noconfirm --needed python-pip
    - python -m venv --system-site-packages venv
    - . venv/bin/activate
    - pip install flake8
    - flake8 --exclude venv

mypy:
  stage: test
  tags:
    - docker
    - linux
  script:
    - pacman -Sy --noconfirm --needed python-pip
    - python -m venv --system-site-packages venv
    - . venv/bin/activate
    - pip install mypy .[mypy]
    - mypy -p steamos_log_submitter
