stages:
  - test

image: registry.gitlab.steamos.cloud/steam/steamos-docker-images/holo-main/base:latest

run_pytest:
  stage: test
  tags:
    - docker
    - linux
  script:
    - pacman -Sy --noconfirm dbus-python python-pip python-pytest
    - pip install .[test]
    - pytest

lint:
  stage: test
  tags:
    - docker
    - linux
  script:
    - pacman -Sy --noconfirm flake8
    - flake8
