stages:
  - test

image: registry.gitlab.steamos.cloud/steam/steamos-docker-images/holo/base:latest

run_pytest:
  stage: test
  tags:
    - docker
    - linux
  script:
    - pacman -Sy --noconfirm python-pip python-pytest
    - pip install .[test]
    - pytest
