[build-system]
requires = ["setuptools"]

[tool.mypy]
warn_unused_configs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"
